Ephenia/Pokeclicker-Scripts

- enhancedautomine.js
I found just using bombs very inefficient and didn't really understand your motivation behind the chisel mode. What this PR does is this:
If a peace of a mining reward is uncovered, chisel will be used on all 9 tiles surrounding it. Thus chiseling rewards will have a higher priority than bombing.
It is still inefficient, because not all tiles surrounding a reward will be relevant, but it's a start and it's much faster at clearing layers than before.
> Use chisel on mining rewards

- enhancedautohatchery.js
Split the Auto Egg / Fossil button into Auto Egg that auto hatches bought eggs and Auto Fossil that auto hatches fossils.
Behaviour when both buttons are on should be exactly as before.
Implements #78.
Slightly reduces the left padding on the Day Care buttons (Pokemon List Sync, Auto Egg and Auto Fossil) so that the entire labels fit into a single line.
> Issue #78 - Split Auto Egg / Fossil into two buttons.

- catchfilterfantasia.user.js
after 04/08/2022 pokeclicker update the attemptCatch function was change to take the route and region as parameter as part of the calculation of the amount of dungeon token to be gained
as the scripts was still calling with only the pokemon as parameters the output would be NaN and the player would always gain a fixed amount of dungeon token
> [BugFix] Dungeon Tokens at 13 after update 

- enhancedautoclicker.user.js
Since update v0.9.17 dungeons can have floors.
i have update dungeonBoard variable to avoid JS error.
It now use DungeonRunner.map.playerPosition().floor to check the current floor to parse.
i've also updated scan(), fullClear() and wander() to check and use Ladders for Boss and Full runs
> [Fix] add floors supports to autoDungeon

- README.md
- enhancedautomine.user.js
-New treasure hunter setting to skip layers with too few of the desired item type
-Merged auto-skipping layers with too few items into the treasure hunter (UI got too cramped)
-Efficiency improvements to when the script surveys, bombs, and uses restores
-Simplified the reset layer code by integrating it more closely with the main game
Improves on #200, implements #132 and #99.
> Treasure hunter improvements (plus efficiency tweaks)

- enhancedautoclicker.user.js
Minor improvment in Champion management.
When we have a champion which is not an E4, we were not able to autofight with a numbered option (but the "ALL" option worked)
Any # selection which is higher than the number of gyms should autofight the champion if available.
Should solve #232 for Leon in Wyndon Stadium
> AutoGym Improvment

- enhancedautohatchery.user.js
Resolves #251 
Because `player.starter()` isn't available any longer, and I couldn't find a way to grab the player starter name without going through the ID first, I opted to change the definition for starterPKMN to search for the starter by ID instead of name.
`player.regionStarters[GameConstants.Region.kanto]()` returns an index value between 0 and 2 (0 and 3 for Kanto, where Pikachu can be selected as a starter). This index value can be used to retrieve the starter Pokemon ID from GameConstants.RegionalStarters, which is a 2-dimensional array containing the ids for each starter in each region.
> Grab starterPKMN by comparing starterID

- enhancedautomine.user.js
Pretty straightforward. Mega stones can now be found in the underground, so this adds the ability to target them with the treasure hunter. Also makes the treasure hunter count gen 8 fossil pieces as fossils, and fixes a small inefficiency where the treasure hunter would still survey when set to find 0 of an item type.
> Add auto-miner mega stone survey support

- README.md
- enhancedautoclicker.user.js
Rewrote most of the autoclicker for improved performance and stability. Noteworthy changes:
Auto Clicker:
-Reworked variable click delay into a variable click multiplier, enabling higher DPS without the performance hits of going beyond 20 ticks per second
-Improved performance
Auto Gym:
-Reworked to restart gym without loading town in between, dramatically improving performance
-Added setting similar to Additional Visual Settings to disable most battle graphics while Auto Gym is running
-All gyms mode currently disabled due to stability issues with the new Auto Gym implementation and not meshing well with the statistics calculator; I left my mostly-functional code for it in and commented out
Auto Dungeon:
-Full clear mode now waits to open chests until right before the boss, decreasing …
> Major autoclicker efficiency overhaul + new features

- custom/catchspeedadjuster.user.js
Fixes formatting of the catch speed settings box. The addition of the pokerus catch setting and corresponding resizing means this no longer spans the entire element.
> Catch Speed Adjuster formatting fix

- README.md
- custom/overnightberries.user.js
- custom/overnightberrygrowth.user.js
Farming lategame berries that take days to grow is extremely annoying if you don't want to leave the game open constantly. This script allows berries to grow while the game is closed.
The script simulates growth for the length of time the game was closed, accounting for auras and mulch. Withered berries replant as usual, but replanted berries do not grow to avoid potential lag after long breaks. Farm helpers are not used and (non-Kasib) mutations do not occur.  There are three modes to choose between, to suit your personal play style:
- Until ripe: Berries grow only until they are ripe. No rush to return to the game, no risk of destroying a carefully-arranged farm setup. The most forgiving option.
- Until withered: Berries continue aging until they wither. A less-forgiving experience more …
> New script: Overnight Berry Growth

- custom/catchspeedadjuster.user.js
- custom/infiniteseasonalevents.user.js
- desktop/app_src/src/scripthandler.js
The new 0.10.11 update made some changes to the game. This broke some scripts, and this PR aims to fix that.
After a few hours of test with the fixes, everything seems fine.
0.10.11 modified the Pokéball selector by adding filters.
I changed the colspan from the script, and moved the Delay Capture checkbox to the bottom.
<table>
<tr align="center">
<td><b>Before fix</b></td>
<td><b>After fix</b></td>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/89878127/236692353-a236f3b8-dbd6-470d-928d-4f274fb12afb.png"></td>
<td> <img src="https://user-images.githubusercontent.com/89878127/236692351-6b823e17-dec9-46d3-974c-efd90b071940.png"></td>
</tr>
</table>
0.10.11 update added new tabs in the Log Book modal. As a consequence, the Scripts tab was moved into it.
I updated the …
> PokéClicker v0.10.11 Catch Speed Adjuster + Scripthandler.js / app.asar fixes. Also Infinite Seasonal Events images fix.

- custom/omegaproteingains.user.js
Updates Omega Protein Games to support the new vitamins. Instead of updating the existing approach of intercepting clicks, I modified it to overwrite `PartyPokemon.useVitamin()` instead. This should make the script much more resilient to future game updates (new vitamins, UI changes, etc).
The script now supports both individual and combined vitamin menus and both adding and removing vitamins. While there's no cap on using Protein or Calcium, I added a limit to the number of Carbos that players can use on each Pokemon to avoid potential glitches from extremely low step counts rounding to 0. The current limit is 70 Carbos, which under the current formula brings any Pokemon above 300 egg steps to exactly 300 steps.
A better approach to the Carbos issue would be to wrap …
> Update omegaproteingains for new vitamin mechanics

- catchfilterfantasia.user.js
Rewriting of pokemon filtering by Route to add "specials" pokemons in filter (Weather dependant, quest dependant, ...)
A check is made to ensure that we do not display duplicates (can occur with special pokemons).
All routes should now give a result.
Related to issue #242
> Listing "special" pokemons in filter

- catchfilterfantasia.user.js
This PR superseeds #315 
By just overloading the `calculatePokeballToUse` instead of overriding the `defeatPokemon` method we become more future-proof and don't do more than the minimal necessary to apply the catch filter.
This should fix #314, you can check that now on dungeons the number of enemies defeated (top-right corner of dungeon map box) is now displayed correctly as the game original `defeatPokemon` procedure is being executed.
Thanks to @umbralOptimatum for suggesting this change
> Change catchFilterFantasia to just overload pokeball catch method

- autobattlefrontier.user.js
- custom/infiniteseasonalevents.user.js
Fixes Infinite Seasonal Events to work with the new game version, plus some code refinements.
> Infinite Seasonal Events update fix

- README.md
- desktop/app_src/src/main.js
- desktop/app_src/src/scripthandler.js
- desktopupdatechecker.js
- scriptfixerupper.user.js
Clarifications in the hopes of fewer basic help questions, especially around scriptfixerupper.
- README edits
- Added scriptfixerupper section
- Further clarified desktop sections
- Added more attention-grabbing links to the support instructions...
- Added the script name to the scriptfixerupper popup
- Changed scriptfixerupper to run before the game loads
- Changed desktop script manager to list scriptfixerupper separately from regular scripts
> Scriptfixerupper and README wording changes

- README.md
- additionalvisualsettings.user.js
- autobattlefrontier.user.js
- custom/autoquestcompleter.user.js
- custom/autosafarizone.user.js
- custom/overnightberrygrowth.user.js
- desktop/README.md
- desktop/app_src/src/main.js
- desktop/app_src/src/scripthandler.js
- desktopupdatechecker.js
- enhancedautoclicker.user.js
- enhancedautomine.user.js
- Enhanced Auto Clicker
- Auto Dungeon now has separate fights and chests modes
- Open all chests without fighting every enemy or vice versa
- New setting to open rare chests when chests mode is off
- Rewrote script to be a class and have fewer global variables cluttering things up
- Closes #75, closes #140, closes #197
- Additional Visual Settings
- Fixed the dock/gym/dungeon menus allowing some sequence breaking
- Auto Safari Zone
- Now enabled in Johto's National Park and Sinnoh's Great Marsh
- In National Park will default to highest-average-token encounter type
- Improved prioritization between land and water encounters
- Closes #354, closes #358
- Scripts with their own settings menus now display in a consistent alphabetical order
- Fixed a couple rare desktop issues
- Readme …
> New Auto Dungeon mode + misc fixes

- additionalvisualsettings.user.js
Currently badges don't display when opening the gyms shortcut modal because `generateRegionGymsList` looks for ".png" files. Badge images seem to be stored as ".svg" files, so this commit makes `generateRegionGymsList` look for ".svg" files and thus allows badges to display in the gyms shortcut modal.
> Fix Badges Not Displaying in Gyms Shortcut Modal

- custom/catchspeedadjuster.user.js
Small edit to the `catchspeedadjuster.user.js` file so the background for the Pokéball modal is not broken and invisible anymore after a certain size.
<table>
<tr align="center">
<td><b>Before fix</b></td>
<td><b>After fix</b></td>
</tr>
<tr>
<td><img src="https://i.imgur.com/jr4QIqU.png"></td>
<td> <img src="https://i.imgur.com/LAGm1ql.png"></td>
</tr>
</table>
> Fix Pokéball modal invisible background for v0.10.18

- enhancedautoclicker.user.js
The update has some click attack performance improvements so the autoclicker's equivalent is no longer necessary. Hopefully will address #377.
> Autoclicker patch for update changes to click attacks

- simpleautofarmer.user.js
I found myself annoyed at having to constantly check the farm to harvest mutated berries and free up space for new mutations, so I adjusted the Auto Replant behavior to account for this.
Now, when Auto Replant is active, berries on tiles with Surprise Mulch will be auto-harvested immediately after growth, and not replanted. Everything else remains unchanged (so berries on tiles with no or any other type of mulch will be harvested at the end of their cycle and replanted as usual).
> [Auto Farmer] Better Auto Replant for mutations

- additionalvisualsettings.user.js
Fixes #385. The other Tampermonkey issue I understand, this one has me baffled. Why does `unsafeWindow` break `window`? If `window` isn't the actual page's `window`, why was it working before?? Tampermonkey your documentation explains none of this!!
> Additional Visual Settings hotfix (again)

- README.md
- custom/autosafarizone.user.js
- enhancedautoclicker.user.js
Added a new Auto Dungeon feature: the script will now complete the current dungeon when you turn it off, rather than stopping mid-dungeon. No more trying to click the button right when fighting the boss! Clicking the button a second time stops exploration immediately, and there's a setting in the settings menu to disable this delayed-stop mode.
I also tweaked the various mode buttons to enable or disable other modes as relevant.
Thanks to @JohnyDL for the inspiration to finish implementing this (#392).
> New Auto Dungeon feature: complete dungeon before turning off

- catchfilterfantasia.user.js
- custom/autosafarizone.user.js
- enhancedautoclicker.user.js
Due to changes with how `player.route()` and `player.town()` works, being changed from a function to a getter, and *effectively* the renaming of ModalUtils, this fixes the following scripts:
- `enhancedautoclicker.user.js`
- `catchfilterfantasia.user.js`
- `autosafarizone.user.js`
~~There is only one part of this update that I don't really have the experience to fix, which is `enhancedautoclicker.user.js:571` where `player.town()` is used with an argument to get the gym's location, and then throws an error which locks the player in the gym screen. I'm currently trying to patch that, and will add another commit afterwards.~~ This has been fixed in 491bcbf, PR is ready for review.
Closes: #396
> [v0.10.20] Fix scripts

- custom/autosafarizone.user.js
Fixed the script crashing after using the seek new or seek pokerus modes in Magikarp Jump when the desired pokemon could spawn in grass but the map didn't generate any grass tiles.
> Auto Safari patch for v0.10.20

- README.md
- additionalvisualsettings.user.js
- autobattlefrontier.user.js
- autobattleitems.user.js
- catchfilterfantasia.user.js
- custom/autoquestcompleter.user.js
- custom/autosafarizone.user.js
- custom/catchspeedadjuster.user.js
- custom/challengemodechanger.user.js
- custom/debugcheatstools.user.js
- custom/discordcodegenerator.user.js
- custom/infiniteseasonalevents.user.js
- custom/oakitemsunlimited.user.js
- custom/omegaproteingains.user.js
- custom/overnightberrygrowth.user.js
- custom/perkypokeruspandemic.user.js
- custom/simpleweatherchanger.user.js
- custom/syntheticshinysynapse.user.js
- enhancedautoclicker.user.js
- enhancedautohatchery.user.js
- enhancedautomine.user.js
- simpleautofarmer.user.js
Rewrote Additional Visual Settings with improvements and fixes for the new version.
Changes:
- Additional Visual Settings
- Added support for disabling graphics in gyms, dungeons, and the battle frontier with separate settings for each
- Added new setting to hide the party attack number (slow to calculate)
- Removed setting to hide pokemon defeated number on routes (not slow to calculate)
- Removed "Disable all notifications" setting as it was suppressing crash notifications*
- Added auto-clicker support setting: if Enhanced Auto Clicker is also installed, it will only disable graphics while the auto clicker is running
- Enhanced Auto Clicker
- Removed disable-graphics settings, as these are now part of AVS.
- All scripts
- Improved crash reporting
*If someone needed this for a particular …
> Additional Visual Settings rework for new update
