additionalvisualsettings.js
autobattlefrontier.js
custom/catchspeedadjuster.js
custom/challengemodechanger.js
custom/discordcodegenerator.js
custom/infiniteseasonalevents.js
custom/oakitemsunlimited.js
custom/omegaproteingains.js
enhancedautoclicker.js
enhancedautohatchery.js
enhancedautomine.js
simpleautofarmer.js

All changes are detailed in the commits to my branch, currently remaining issues are mostly in the events script

Update to work on pokeclicker 0.9.1

---

README.md
additionalvisualsettings.js
autobattlefrontier.js
custom/autoquestcompleter.js
custom/catchspeedadjuster.js
custom/challengemodechanger.js
custom/discordcodegenerator.js
custom/infiniteseasonalevents.js
custom/oakitemsunlimited.js
custom/omegaproteingains.js
custom/simpleweatherchanger.js
enhancedautoclicker.js
enhancedautohatchery.js
enhancedautomine.js
simpleautofarmer.js

Updated the loading of all scripts to make it more efficient and consistent. Added 2 new scripts to the custom folder. Updated infiniteseasonalevents.js to fix the custom event pokemon not being removed properly and events starting when disabled.

Updated loading and events

---

README.md
additionalvisualsettings.js
custom/infiniteseasonalevents.js
custom/simpleweatherchanger.js
enhancedautoclicker.js

Improved auto dungeon and fixed weather evolutions

---

custom/infiniteseasonalevents.js

Made the events load independent of order and changed local storage to load them properly. This will reset the active events for this version because the names of the variables have changed. Additionally future proofed the script by adding events even if we don't have the images yet.

Changed event order

---

autobattlefrontier.js

Added button that ignores the max stage when on, then resets only if it takes more than one click to defeat the enemy. Should resolve partially #67 
N-shot should likewise be really easy to implement with existing function oneClick()

Added One Click Attack functionality

---

enhancedautoclicker.js

Looking to resolve Issue #68 
Created logic to check if 5 is selected, then loops through a variable stored in localStorage from 0 to 4. If 5, then resets back to 0.

Add Option to loop through League

---

additionalvisualsettings.js

Added catch spinner removal, to increase performance by not updating the DOM. 100% based on previous settings, just new checkbox and different HTML class targeted.

[Add] Catch Spinner removal

---

simpleautofarmer.js

And rewrite the code
Show issue #106

Issue #106 - Split button Farm into Plant/Harvest

---

enhancedautoclicker.js

FIx battle Temporary (battle ultra wormhole)

---

custom/autoquestcompleter.js

Add ';' at the end of the block
Remove useless space (trim)

Issue 115 Fix bug -> Add clearInterval(autoQuest); to stop process where "auto OFF"

---

README.md
additionalvisualsettings.user.js
autobattlefrontier.user.js
catchfilterfantasia.user.js
custom/autoquestcompleter.user.js
custom/catchspeedadjuster.user.js
custom/challengemodechanger.user.js
custom/discordcodegenerator.user.js
custom/infiniteseasonalevents.user.js
custom/oakitemsunlimited.user.js
custom/omegaproteingains.user.js
custom/simpleweatherchanger.user.js
enhancedautoclicker.user.js
enhancedautohatchery.user.js
enhancedautomine.user.js
simpleautofarmer.user.js

2nd PR but this time with the repo up to date :)
- I changed all files extensions to .user.js (in the readme too), so that tampermonkey can automatically add the script upon clicking on the "raw" button.
- I also added the "@updateURL" field in the headers so that the script can be automatically updated by tampermonkey
Note: all fixes work with tampermonkey, but have not been tested with others userscripts managers

Changed all files to .user.js and added @updateURL field #137

---

custom/autoquestcompleter.user.js

Reverts Ephenia/Pokeclicker-Scripts#114

Revert "Issue 115 Fix bug -> Add clearInterval(autoQuest); to stop process where "auto OFF""

---

custom/infiniteseasonalevents.user.js

Hi, is it volontaire ? red spearow, grinch celebi and Elf Munchlax are missing.
i think it should appear like this

Fixing Icons pokemon missing in infiniteseasonalevents.user.js

---

enhancedautohatchery.user.js

Fix issue: https://github.com/Ephenia/Pokeclicker-Scripts/issues/154
- Replace  BreedingController.filter by BreedingFilters
- Add property .value() when necessary

Fix AutoHatchery for Pokeclicker 0.9.6

---

LICENSE
additionalvisualsettings.user.js
autobattlefrontier.user.js
autobattleitems.user.js
catchfilterfantasia.user.js
custom/autoquestcompleter.user.js
custom/catchspeedadjuster.user.js
custom/challengemodechanger.user.js
custom/discordcodegenerator.user.js
custom/infiniteseasonalevents.user.js
custom/oakitemsunlimited.user.js
custom/omegaproteingains.user.js
custom/perkypokeruspandemic.user.js
custom/simpleweatherchanger.user.js
custom/syntheticshinysynapse.user.js
enhancedautoclicker.user.js
enhancedautohatchery.user.js
enhancedautomine.user.js
scriptfixerupper.user.js
simpleautofarmer.user.js

Since It's not real script change, I did not increase the version number.
I hate default values, because they often end up changing :)
Since there is no copyright, GNU3?

Complete Userscript Header

---

enhancedautohatchery.user.js

Filter by pokerus

---

autobattlefrontier.user.js

Auto-battle frontier stage limit confirm button

---

desktop/app_src/src/scripthandler.js

I hadn't heard of the &lt;biv&gt;ision HTML tag before :p

Scripthandler typo fix

---

additionalvisualsettings.user.js

Fixes several Additional Visual Settings issues, mainly with the gym and dungeon shortcut lists.

Additional Visual Settings fixes

---

enhancedautoclicker.user.js

- Tweaked wording to make it clearer what the numbers represent
- Added another display setting to alternatively show the raw number of ticks per second (out of 20) instead of percentage

Auto clicker statistics tweaks

---

enhancedautohatchery.user.js

Now includes the hatchery dropdown that filters on mega evolution status, and sorts based on the hatchery sorting dropdown instead of the main screen party sort.

Update autoHatchery to include Mega, sort by hatchery selection

---

README.md
additionalvisualsettings.user.js
custom/overnightberrygrowth.user.js
enhancedautoclicker.user.js

Of all the silly bugs I've caused, one extra keyword breaking the entire game is pretty up there
Fixes #322.

Script hotfixes

---

desktop/app_src/src/main.js
desktopupdatechecker.js

Fixes issue where script manager could incorrectly say there were script updates to download.

Desktop minor patch

---

desktop/app_src/src/main.js
desktop/app_src/src/scripthandler.js
desktopupdatechecker.js

Small patch to prevent potential race conditions if a user tried to load their save before all scripts had been executed. The game will now only load once all scripts have run.

Desktop proofing against race conditions

---

README.md
additionalvisualsettings.user.js
autobattlefrontier.user.js
custom/autoquestcompleter.user.js
custom/overnightberrygrowth.user.js
custom/simpleweatherchanger.user.js
enhancedautoclicker.user.js
enhancedautohatchery.user.js
enhancedautomine.user.js
simpleautofarmer.user.js

- Additional Visual Settings
- Added optimize vitamins feature, found in all-vitamins menu
- Closes #317
- Added inventory shortcut button to the top right
- Enhanced Auto Clicker
- Added support for chest tiers to both Farm and Boss modes
- Minor statistics improvements
- Minor fixes
- Closes #212, closes #303, closes #309
- Enhanced Auto Hatchery
- Rewrote for major performance improvements; most notably it now only runs when the hatchery registers egg steps
- Fixed pokerus mode!
- Closes #165, closes #304
- Now always uses hatchery filters and sorting
- Closes #264
- Fixes memory leak from duplicate sorting loops  
- Enhanced Auto Miner
- Small energy-efficiency improvement as suggested [here](https://github.com/Ephenia/Pokeclicker-Scripts/issues/246#issuecomment-1658060637)
- …

Assorted script updates, fixes, improvements

---

custom/perkypokeruspandemic.user.js

Fixes #333 by making PPP compatible with the new auto hatchery, as well as less likely to cause future breakage.

Perky Pokerus Pandemic patch

---

enhancedautomine.user.js

Minor automine fix

---

autobattlefrontier.user.js

Minor autobattlefrontier patch

---

additionalvisualsettings.user.js
autobattlefrontier.user.js
custom/perkypokeruspandemic.user.js

Done in by one missing character this time (oops) (unforgivable) (bereft)

More minor patches

---

additionalvisualsettings.user.js
autobattleitems.user.js
catchfilterfantasia.user.js
custom/autoquestcompleter.user.js
custom/catchspeedadjuster.user.js
custom/challengemodechanger.user.js
custom/discordcodegenerator.user.js
custom/infiniteseasonalevents.user.js
custom/oakitemsunlimited.user.js
custom/omegaproteingains.user.js
custom/overnightberrygrowth.user.js
custom/perkypokeruspandemic.user.js
custom/simpleweatherchanger.user.js
custom/syntheticshinysynapse.user.js
desktop/app_src/src/main.js
enhancedautoclicker.user.js
enhancedautohatchery.user.js
enhancedautomine.user.js
scriptfixerupper.user.js
simpleautofarmer.user.js

- Fixes #340 where scripts would be initialized multiple times in debug mode
- scriptfixerupper fixes and desktop support

Desktop bug fixes and scriptfixerupper support

---

README.md

Made some mistakes in the README formatting and left the version bump out of the packed app.asar, whoops ^^;

README formatting and asar version fixes

---

custom/debugcheats.user.js
custom/debugcheatstools.user.js

Was looking to edit my save for test purposes, then did this.
Correspond to issue #34
Maybe a bit too game breaker...

Debug tools

---

additionalvisualsettings.user.js
enhancedautohatchery.user.js

New update's dropping soon and will break the autohatchery, so here's the fix ready to go.

Preemptive autohatchery fix for game update

---

enhancedautohatchery.user.js

Fix for the other update breakage I wasn't aware of. Fixes fossil mode, plus now prioritizes uncaught fossils. Also made some performance improvements.
Closes #373, closes #376.

Auto Hatchery fossil fix

---

desktop/app_src/src/main.js
desktopupdatechecker.js

Fixes a desktop bug that in any reasonable world wouldn't be enough to crash the whole game, Javascript why are you like this

Fix rare desktop crash

---

additionalvisualsettings.user.js
autobattlefrontier.user.js
autobattleitems.user.js
catchfilterfantasia.user.js
custom/autoquestcompleter.user.js
custom/autosafarizone.user.js
custom/catchspeedadjuster.user.js
custom/challengemodechanger.user.js
custom/debugcheatstools.user.js
custom/discordcodegenerator.user.js
custom/infiniteseasonalevents.user.js
custom/oakitemsunlimited.user.js
custom/omegaproteingains.user.js
custom/overnightberrygrowth.user.js
custom/perkypokeruspandemic.user.js
custom/simpleweatherchanger.user.js
custom/syntheticshinysynapse.user.js
enhancedautoclicker.user.js
enhancedautohatchery.user.js
enhancedautomine.user.js
scriptfixerupper.user.js
simpleautofarmer.user.js

Turns out that auto dungeon was restarting the dungeon faster than dungeon boss quests could detect completion. Fixes #371.

Minor fixes and improved crash handling

---

README.md
additionalvisualsettings.user.js
autobattleitems.user.js
catchfilterfantasia.user.js
custom/autoquestcompleter.user.js
custom/autosafarizone.user.js
custom/catchspeedadjuster.user.js
custom/challengemodechanger.user.js
custom/debugcheatstools.user.js
custom/discordcodegenerator.user.js
custom/infiniteseasonalevents.user.js
custom/oakitemsunlimited.user.js
custom/omegaproteingains.user.js
custom/overnightberrygrowth.user.js
custom/perkypokeruspandemic.user.js
custom/simpleweatherchanger.user.js
custom/syntheticshinysynapse.user.js
enhancedautohatchery.user.js
enhancedautomine.user.js
scriptfixerupper.user.js
simpleautofarmer.user.js

Fixed (almost) every script crashing on Tampermonkey. Figures that the update to improve error messages would instead make it worse somehow. I blame Tampermonkey's poor documentation.

Tampermonkey unsafeWindow hotfix

---

enhancedautoclicker.user.js

Fixed an issue with the auto dungeon's delayed restart, where turning the mode off at the right instant left you in the dungeon after defeating the boss. That one's a My Bad
Fixes #392

Fix auto dungeon restart softlock after boss

---

enhancedautoclicker.user.js

Fixed a couple small edge case issues for the new Auto Dungeon delayed stop feature that might prevent the mode from turning off when intended. Hopefully nothing anyone ran into but better safe than sorry.

Quick fix for Auto Dungeon delayed stop

---

additionalvisualsettings.user.js
enhancedautoclicker.user.js

Fixes potential conflicts with the new Dungeon Guides mechanic and makes Auto Dungeon's slow stop feature more consistent. With #397 this should make autoclicker work with the new update.
Edit: Plus an AVS fix for the optimize vitamins button.

Auto Dungeon update fixes
